# tap "cirruslabs/cli"
brew "bottom"
# brew "gh"
# brew "go"
brew "go-task"
# brew "hadolint"
# brew "mas"
# brew "node"
# brew "terraform"
# brew "zsh-autocomplete"
# brew "cirruslabs/cli/tart"
# cask "battery"
# cask "bitwarden"
# cask "brave-browser"
# cask "dbeaver-community"
# cask "discord"
# cask "docker"
# cask "ghostty"
# cask "google-chrome"
# cask "google-cloud-sdk"
# cask "google-drive"
# cask "google-japanese-ime"
# cask "jordanbaird-ice"
# cask "karabiner-elements"
# cask "logi-options+"
# cask "meetingbar"
# cask "monitorcontrol"
# cask "notion"
# cask "postman"
# cask "raycast"
# cask "readdle-spark"
# cask "scroll-reverser"
# cask "slack"
# cask "spotify"
# cask "steam"
# cask "visual-studio-code"
# cask "zen-browser"
# mas "Kindle", id: 302584613
# mas "LINE", id: 539883307
