version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - cirruslabs
  - fileage
  - ghostty
  - kamono
  - Karabiner
  - mitchellh
  - pkgs
  - samber
  - sonoma
  - Taskfile
  - tmpl
  - wasd
ignoreWords: []
import: []
