version: "0.2"
ignorePaths: [Brewfile]
dictionaryDefinitions: []
dictionaries: []
words:
  - cirruslabs
  - fileage
  - ghostty
  - kamono
  - kamonomakoto
  - Karabiner
  - mitchellh
  - pkgs
  - samber
  - shellenv
  - sonoma
  - Taskfile
  - tfaa
  - tmpl
  - wasd
ignoreWords: []
import: []
