version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - cirruslabs
  - fileage
  - ghostty
  - kamono
  - mitchellh
  - pkgs
  - sonoma
  - Taskfile
  - tmpl
ignoreWords: []
import: []
