version: "0.2"
ignorePaths: [
  "./Brewfile",
  "vscode-extensions"
]
dictionaryDefinitions: []
dictionaries: []
words:
  - ghostty
  - karabiner
  - Taskfile
  - taskfiles
ignoreWords: []
import: []
