# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

includes:
  brew: "./taskfiles/brew.yml"
  git: "./taskfiles/git.yml"

tasks:
  init:
    cmds:
      - task: home-task # Initialize Taskfile
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" # Install Oh My Zsh
      - task: load-zsh-aliases # Load Zsh Aliases
      - task: setup-karabiner # Setup Karabiner-Elements
      - mkdir -p ~/.config/ghostty && ln -sf $(pwd)/ghostty.config ~/.config/ghostty/config # Link Ghostty Config

  load-zsh-aliases:
    cmds:
      - echo 'source $HOME/macos-setup/zsh_alias.sh' >> ~/.zshrc
    status:
      - test $LOAD_ALIAS = true

  load-zsh-scripts:
    cmds:
      - echo 'source $HOME/macos-setup/zsh_script.sh' >> ~/.zshrc
    status:
      - test $LOAD_SCRIPT = true

  home-task:
    desc: Initialize Taskfile
    cmds:
      - 'echo ''version: "3"'' > ~/Taskfile.yml'
      - echo '' >> ~/Taskfile.yml
      - echo 'includes:' >> ~/Taskfile.yml
      - echo '  brew:' >> ~/Taskfile.yml
      - 'echo ''    taskfile: "{{.REPO}}/taskfiles/brew.yml"'' >> ~/Taskfile.yml'
      - 'echo ''    dir: "{{.REPO}}"'' >> ~/Taskfile.yml'
      - echo '  git:' >> ~/Taskfile.yml
      - 'echo ''    taskfile: "{{.REPO}}/taskfiles/git.yml"'' >> ~/Taskfile.yml'
      - 'echo ''    dir: "{{.REPO}}"'' >> ~/Taskfile.yml'
      - cat ~/Taskfile.yml
    vars:
      REPO:
        sh: pwd
    silent: true

  setup-karabiner:
    prompt: karabiner-elementsを起動したことを確認しましたか?
    cmds:
      - ln -sf $(pwd)/karabiner.json ~/.config/karabiner/karabiner.json
