version: 3

output: prefixed

tasks:
  default:
    cmds:
      - task mac

  mac:
    desc: "動作検証用 MacOSのVMを立ち上げる"
    cmds:
      - tart stop {{.VM_NAME}} || true
      - tart clone ghcr.io/cirruslabs/macos-sonoma-vanilla:latest {{.VM_NAME}}
      - tart run --dir=macos-setup:~/macos-setup:ro {{.VM_NAME}}
    vars:
      VM_NAME: mac
    watch: true
    sources:
      - "./**/*"
      - exclude: "./LaunchAgents/log/*"

  init:
    cmds:
      - git clone -b feat/brew-mise https://github.com/Mkamono/macos-setup.git ~/macos-setup
      - cd ~/macos-setup && task plist && task sync

  plist:
    desc: "launchdの設定ファイルを生成する"
    dir: ./LaunchAgents
    cmds:
      - rm -rf ./log
      - go run main.go
    sources:
      - "./*.tmpl.plist"
      - "./main.go"
      - "../Taskfile.yml"

  sync:
    desc: "macos-setupを同期する。launchdに登録されている"
    silent: true
    prefix: "{{.DATE}}"
    vars:
      DATE:
        sh: date '+%Y/%m/%d %H:%M:%S'
    cmds:
      - echo "Sync completed."
    deps:
      - task: rsync
        vars:
          SRC: ./config/.gitconfig
          DST: ~/.gitconfig
      - task: rsync
        vars:
          SRC: ./config/zsh/.zprofile
          DST: ~/.zprofile
      - task: rsync
        vars:
          SRC: ./config/zsh/.zshrc
          DST: ~/.zshrc
      - task: rsync
        vars:
          SRC: ./config/mise/config.toml
          DST: ~/.config/mise/config.toml
      - task: rsync
        vars:
          SRC: ./config/ghostty/config
          DST: ~/Library/Application\ Support/com.mitchellh.ghostty/config

  rsync:
    internal: true
    silent: true
    requires:
      vars: [SRC, DST]
    cmds:
      - rsync --update {{.SRC}} {{.DST}}
      - rsync --update {{.DST}} {{.SRC}}
    status:
      - cmp {{.SRC}} {{.DST}}
