version: 3

output: prefixed
# silent: true

tasks:
  default:
    cmds:
      - task mac

  mac:
    desc: "動作検証用 MacOSのVMを立ち上げる"
    cmds:
      - tart stop {{.VM_NAME}} || true
      - tart clone ghcr.io/cirruslabs/macos-sonoma-vanilla:latest {{.VM_NAME}}
      - tart run --dir=macos-setup:${HOME}/macos-setup:ro {{.VM_NAME}}
    vars:
      VM_NAME: mac
    watch: true

  init:
    cmds:
      - git clone -b feat/brew-mise https://github.com/Mkamono/macos-setup.git ${HOME}/macos-setup
      - cd ${HOME}/macos-setup && task plist && task sync

  plist:
    desc: "launchdの設定ファイルを生成する"
    dir: ./LaunchAgents
    cmds:
      - rm -rf ./log
      - go run main.go
    sources:
      - "./*.tmpl.plist"
      - "./main.go"
      - "../Taskfile.yml"

  sync:
    desc: "macos-setupを同期する。launchdに登録されている"
    prefix: "{{.DATE}}"
    vars:
      DATE:
        sh: date '+%Y/%m/%d %H:%M:%S'
    cmds:
      - echo "Sync completed."
    deps:
      - task: rsync
        vars:
          SRC: config/.gitconfig
          DST: ${HOME}/.gitconfig
      - task: rsync
        vars:
          SRC: config/zsh/.zprofile
          DST: ${HOME}/.zprofile
      - task: rsync
        vars:
          SRC: config/zsh/.zshrc
          DST: ${HOME}/.zshrc
      - task: rsync
        vars:
          SRC: config/mise/config.toml
          DST: ${HOME}/.config/mise/config.toml
      - task: rsync
        vars:
          SRC: config/ghostty/config
          DST: ${HOME}/.config/ghostty/config
      - task: rsync
        vars:
          SRC: config/Code/User/settings.json
          DST: ${HOME}/Library/Application Support/Code/User/settings.json
      - task: rsync
        vars:
          SRC: config/Code/User/keybindings.json
          DST: ${HOME}/Library/Application Support/Code/User/keybindings.json
      - task: rsync
        vars:
          SRC: config/karabiner/karabiner.json
          DST: ${HOME}/.config/karabiner/karabiner.json
      - task: vscode-extension
      - task: brewfile
      - task: karabiner-format

  rsync:
    internal: true
    requires:
      vars: [SRC, DST]
    cmds:
      - mkdir -p "$(dirname '{{.DST}}')"
      - rsync --update "{{.SRC}}" "{{.DST}}"
      - rsync --update "{{.DST}}" "{{.SRC}}"
    status:
      - cmp "{{.SRC}}" "{{.DST}}"

  rsync-test:
    cmds:
      - task: rsync
        vars:
          SRC: config/.gitconfig
          DST: Library/Application Support/Code/User/keybindings.json

  vscode-extension:
    vars:
      frequency: 600 # 10分
    cmds:
      - mkdir -p $(dirname ./config/Code/User/extensions)
      - code --list-extensions > ./config/Code/User/extensions
    status:
      - go run ./pkgs/fileage/main.go -seconds {{.frequency}} ./config/Code/User/extensions

  brewfile:
    vars:
      frequency:
        sh: echo $((60*60*24)) # 1日
    cmds:
      - mkdir -p ./config
      - brew bundle dump -f --no-vscode --file=./config/Brewfile
    status:
      - go run ./pkgs/fileage/main.go -seconds {{.frequency}} ./config/Brewfile

  karabiner-format:
    cmds:
      - mkdir -p ${HOME}/.config/karabiner
      - cd ./pkgs/karabiner && go run main.go format ${HOME}/.config/karabiner/karabiner.json
      - cd ./pkgs/karabiner && go run main.go format ../../config/karabiner/karabiner.json
    sources:
      - "${HOME}/.config/karabiner/karabiner.json"
      - "./config/karabiner/karabiner.json"
