# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

includes:
  brew: "./taskfiles/brew.yml"
  git: "./taskfiles/git.yml"
  karabiner: "./taskfiles/karabiner.yml"

tasks:
  init:
    cmds:
      - task: home-task # Initialize Taskfile
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" # Install Oh My Zsh
      - echo "source $HOME/macos-setup/zsh/entrypoint.sh" >> ~/.zshrc # Load Zsh Settings
      - task: setup-karabiner # Setup Karabiner-Elements
      - rm -rf ~/Library/Application\ Support/com.mitchellh.ghostty
      - mkdir -p ~/.config/ghostty && ln -sf $(pwd)/ghostty.config ~/.config/ghostty/config # Link Ghostty Config

  home-task:
    desc: Initialize Taskfile
    vars:
      REPO:
        sh: pwd
    cmds:
      - cp templates/Taskfile.yml.tmpl ~/Taskfile.yml
      - sed -i '' "s|@REPO|$(pwd)|g" ~/Taskfile.yml

  setup-karabiner:
    prompt: karabiner-elementsを起動したことを確認しましたか?
    cmds:
      - ln -sf $(pwd)/karabiner.json ~/.config/karabiner/karabiner.json
