version: 3

output: prefixed
silent: true

tasks:
  default:
    desc: "動作検証用 MacOSのVMを立ち上げる"
    cmds:
      - tart stop {{.VM_NAME}} || true
      - tart clone ghcr.io/cirruslabs/macos-sonoma-vanilla:latest {{.VM_NAME}}
      - tart run --dir=macos-setup:~/macos-setup:ro {{.VM_NAME}}
    vars:
      VM_NAME: mac

  init:
    cmds:
      - cp -r . ~/macos-setup
      - cd ~/macos-setup && task plist && task sync

  plist:
    desc: "launchdの設定ファイルを生成する"
    dir: ./LaunchAgents
    cmds:
      - rm -rf ./log
      - go run main.go
    sources:
      - "./*.tmpl.plist"
      - "./main.go"
      - "../Taskfile.yml"

  sync:
    desc: "macos-setupを同期する。launchdに登録されている"
    prefix: "{{.DATE}}"
    vars:
      DATE:
        sh: date '+%Y/%m/%d %H:%M:%S'
    cmds:
      - echo "Sync completed."
    deps:
      - for:
          [
            ghostty/config,
            mise/config.toml,
            karabiner/karabiner.json,
            fish/functions/fish_prompt.fish,
            fish/fish_variables,
            fish/config.fish,
          ]
        task: rsync
        vars:
          SRC: .config/{{.ITEM}}
          DST: ~/.config/{{.ITEM}}
      - task: rsync
        vars:
          SRC: .config/.gitconfig
          DST: ~/.gitconfig
      - task: rsync
        vars:
          SRC: .config/Code/User/settings.json
          DST: ~/Library/Application\ Support/Code/User/settings.json
      - task: rsync
        vars:
          SRC: .config/Code/User/keybindings.json
          DST: ~/Library/Application\ Support/Code/User/keybindings.json
      - task: vscode-extension
      - task: brewfile
      - task: karabiner-format

  rsync:
    internal: true
    requires:
      vars: [SRC, DST]
    cmds:
      - mkdir -p "$(dirname {{.DST}})"
      - rsync --update {{.SRC}} {{.DST}}
      - rsync --update {{.DST}} {{.SRC}}
    status:
      - cmp "{{.SRC}}" "{{.DST}}"

  vscode-extension:
    vars:
      frequency: 600 # 10分
    cmds:
      - mkdir -p $(dirname ./.config/Code/User/extensions)
      - code --list-extensions > ./.config/Code/User/extensions
    status:
      - go run ./pkgs/fileage/main.go -seconds {{.frequency}} ./.config/Code/User/extensions

  brewfile:
    vars:
      frequency:
        sh: echo $((60*60*24)) # 1日
    cmds:
      - mkdir -p ./.config
      - brew bundle dump -f --no-vscode --file=./.config/Brewfile
    status:
      - go run ./pkgs/fileage/main.go -seconds {{.frequency}} ./.config/Brewfile

  karabiner-format:
    cmds:
      - mkdir -p ~/.config/karabiner
      - cd ./pkgs/karabiner && go run main.go format ~/.config/karabiner/karabiner.json
      - cd ./pkgs/karabiner && go run main.go format ../../.config/karabiner/karabiner.json
    sources:
      - "~/.config/karabiner/karabiner.json"
      - "./.config/karabiner/karabiner.json"
