# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

includes:
  brew: "./taskfiles/brew.yml"
  git: "./taskfiles/git.yml"
  karabiner: "./taskfiles/karabiner.yml"
  vscode: "./taskfiles/vscode.yml"

tasks:
  init:
    cmds:
      - task: home-task # Initialize Taskfile
      - task: setup-karabiner # Setup Karabiner-Elements
      - ln -sf $XDG_CONFIG_HOME/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json # Link VSCode Settings

  home-task:
    desc: Initialize Taskfile
    vars:
      REPO:
        sh: pwd
    cmds:
      - cp templates/Taskfile.yml.tmpl ~/Taskfile.yml
      - sed -i '' "s|@REPO|$(pwd)|g" ~/Taskfile.yml

  setup-karabiner:
    prompt: karabiner-elementsを起動したことを確認しましたか?
    cmds:
      - ln -sf $(pwd)/karabiner.json ~/.config/karabiner/karabiner.json
