version: 3

output: prefixed
silent: true

vars:
  MY_GO_BIN: "{{.ROOT_DIR}}/pkgs/bin"

tasks:
  default:
    desc: 動作検証用 MacOSのVMを立ち上げる
    cmds:
      - tart stop {{.VM_NAME}} || true
      - tart clone ghcr.io/cirruslabs/macos-sonoma-vanilla:latest {{.VM_NAME}}
      - tart run --dir=macos-setup:~/macos-setup:ro {{.VM_NAME}}
    vars:
      VM_NAME: mac

  init:
    cmds:
      - cp -r . ~/macos-setup
      - cd ~/macos-setup && task plist && task sync

  plist:
    desc: launchdの設定ファイルを生成する
    dir: ./LaunchAgents
    cmds:
      - rm -rf ./log
      - go run main.go
    sources:
      - "./*.tmpl.plist"
      - "./main.go"
      - "../Taskfile.yml"

  sync:
    desc: macos-setupを同期する。launchdに登録されている
    vars:
      DATE:
        sh: date '+%Y/%m/%d %H:%M:%S'
      CONFIG_FIlES:
        sh: cd home/.config/ && git ls-files
    prefix: "{{.DATE}}"
    cmds:
      - echo "Sync completed."
    deps:
      - task: vscode-extension
      - task: brewfile
      - task: karabiner-format
      - for: { var: CONFIG_FIlES }
        task: rsync
        vars:
          SRC: home/.config/{{.ITEM}}
          DST: ~/.config/{{.ITEM}}
      - for:
          [
            .gitconfig,
            .docker/config.json,
            .colima/default/colima.yaml,
            .battery/maintain.percentage,
            .minikube/config/config.json,
            Library/Application\ Support/Code/User/settings.json,
            Library/Application\ Support/Code/User/keybindings.json,
          ]
        task: rsync
        vars:
          SRC: home/{{.ITEM}}
          DST: ~/{{.ITEM}}
      - task: delete-empty-dir

  rsync:
    internal: true
    requires:
      vars: [SRC, DST]
    cmds:
      - mkdir -p "$(dirname {{.DST}})"
      - mkdir -p "$(dirname {{.SRC}})"
      - test -f {{.SRC}} && rsync --update {{.SRC}} {{.DST}} || echo "not found {{.SRC}}"
      - rsync --update {{.DST}} {{.SRC}}
    status:
      - cmp "{{.SRC}}" "{{.DST}}"

  vscode-extension:
    vars:
      frequency: 600 # 10分
    cmds:
      - code --list-extensions > /tmp/extensions
      - cp /tmp/extensions "home/Library/Application Support/Code/User/extensions"
    status:
      - "{{.MY_GO_BIN}}/fileage -seconds {{.frequency}} home/Library/Application\ Support/Code/User/extensions"

  brewfile:
    vars:
      frequency: 3600 # 1時間
    cmd: brew bundle dump -f --no-vscode --file=home/Brewfile
    status:
      - "{{.MY_GO_BIN}}/fileage -seconds {{.frequency}} home/Brewfile"

  karabiner-format:
    cmds:
      - mkdir -p ~/.config/karabiner
      - "{{.MY_GO_BIN}}/karabiner format ~/.config/karabiner/karabiner.json"
      - "{{.MY_GO_BIN}}/karabiner format {{.ROOT_DIR}}/home/.config/karabiner/karabiner.json"
    sources:
      - "~/.config/karabiner/karabiner.json"
      - "{{.ROOT_DIR}}/home/.config/karabiner/karabiner.json"

  build-bin:
    desc: Goのバイナリをビルドする
    watch: true
    dir: pkgs
    vars:
      PKGS:
        sh: ls | grep -vw "bin"
    cmds:
      - for: { var: PKGS }
        cmd: go build -C {{.ITEM}} -o {{.MY_GO_BIN}}/{{.ITEM}}
    sources:
      - "./**/*.go"

  all-sync:
    desc: macos-setupを同期する。launchdに登録されていない
    dir: home
    cmds:
      - rsync -av --exclude-from=rsync_ignore.txt ~/ ./

  delete-empty-dir:
    desc: 空のディレクトリを削除する
    dir: home
    cmds:
      - find . -type d -empty -delete
