version: 3

output: prefixed
silent: true

tasks:
  default:
    desc: "動作検証用 MacOSのVMを立ち上げる"
    cmds:
      - tart stop {{.VM_NAME}} || true
      - tart clone ghcr.io/cirruslabs/macos-sonoma-vanilla:latest {{.VM_NAME}}
      - tart run --dir=macos-setup:~/macos-setup:ro {{.VM_NAME}}
    vars:
      VM_NAME: mac

  init:
    cmds:
      - cp -r . ~/macos-setup
      - cd ~/macos-setup && task plist && task sync

  plist:
    desc: "launchdの設定ファイルを生成する"
    dir: ./LaunchAgents
    cmds:
      - rm -rf ./log
      - go run main.go
    sources:
      - "./*.tmpl.plist"
      - "./main.go"
      - "../Taskfile.yml"

  sync:
    desc: "macos-setupを同期する。launchdに登録されている"
    vars:
      DATE:
        sh: date '+%Y/%m/%d %H:%M:%S'
      CONFIG_FIlES:
        sh: cd home/.config/ && git ls-files
    prefix: "{{.DATE}}"
    cmd: echo "Sync completed."
    deps:
      - task: vscode-extension
      - task: brewfile
      - task: karabiner-format
      - for: { var: CONFIG_FIlES }
        task: rsync
        vars:
          SRC: home/.config/{{.ITEM}}
          DST: ~/.config/{{.ITEM}}
      - task: rsync
        vars:
          SRC: home/.gitconfig
          DST: ~/.gitconfig
      - task: rsync
        vars:
          SRC: home/Library/Application\ Support/Code/User/settings.json
          DST: ~/Library/Application\ Support/Code/User/settings.json
      - task: rsync
        vars:
          SRC: home/Library/Application\ Support/Code/User/keybindings.json
          DST: ~/Library/Application\ Support/Code/User/keybindings.json

  rsync:
    internal: true
    requires:
      vars: [SRC, DST]
    cmds:
      - mkdir -p "$(dirname {{.DST}})"
      - rsync --update {{.SRC}} {{.DST}}
      - rsync --update {{.DST}} {{.SRC}}
    status:
      - cmp "{{.SRC}}" "{{.DST}}"

  vscode-extension:
    vars:
      frequency: 600 # 10分
    cmd: code --list-extensions > "home/Library/Application Support/Code/User/extensions"
    status:
      - go run pkgs/fileage/main.go -seconds {{.frequency}} home/Library/Application\ Support/Code/User/extensions

  brewfile:
    vars:
      frequency:
        sh: echo $((60*60*24)) # 1日
    cmd: brew bundle dump -f --no-vscode --file=home/.config/Brewfile
    status:
      - go run pkgs/fileage/main.go -seconds {{.frequency}} home/.config/Brewfile

  karabiner-format:
    cmds:
      - mkdir -p ~/.config/karabiner
      - cd pkgs/karabiner && go run main.go format ~/.config/karabiner/karabiner.json
      - cd pkgs/karabiner && go run main.go format {{.ROOT_DIR}}/home/.config/karabiner/karabiner.json
    sources:
      - "~/.config/karabiner/karabiner.json"
      - "{{.ROOT_DIR}}/home/.config/karabiner/karabiner.json"
