# ~/.config/mise/config.toml
[tools]
# bottom = "latest"
# gcloud = "latest"
# gh = "latest"
# go = "latest"
# kubectl = "latest"
# node = "latest"
# task = "latest"
# terraform = "latest"
# colima = "latest"
# lima = "latest"
# minikube = "latest"

[env]
_.path = ["~/go/bin"]
XDG_CONFIG_HOME = "{{env.HOME}}/macos-setup/.config"
TF_CLI_ARGS_plan = "--parallelism=50"
TF_CLI_ARGS_apply = "--parallelism=50"

[settings]
experimental = true
