[tools]
"go:github.com/Mkamono/asciinemaForLLM" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:ccusage" = "latest"
python = "latest"
task = "latest"

[env]
_.path = ["~/go/bin", "{{env.HOME}}/macos-setup/pkgs/bin"]
XDG_CONFIG_HOME = "{{env.HOME}}/macos-setup/home/.config"
TF_CLI_ARGS_plan = "--parallelism=50"
TF_CLI_ARGS_apply = "--parallelism=50"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "node"]
